[general]
network_check_url=http://wifi.vivo.com.cn/generate_204
server_check_url=http://cp.cloudflare.com/generate_204
fallback_udp_policy=reject
geo_location_checker=http://ip-api.com/json/?fields=11024
resource_parser_url = https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/resource-parser.js
dns_exclusion_list=*.cmpassport.com, *.jegotrip.com.cn, *.icitymobile.mobi, id6.me, *.cmbchina.com
dns_reject_domain_behavior=nxdomain
excluded_routes=192.168.0.0/16, 172.16.0.0/12, 100.64.0.0/10, 10.0.0.0/8
[dns]
;prefer-doh3
no-system
no-ipv6
server=8.8.4.4
server=8.8.8.8
doh-server=https://dns.google/dns-query
[policy]
[server_remote]
[filter_remote]
https://raw.githubusercontent.com/Jovanykoch/rules/rel/reject.quanx, tag=reject, force-policy=reject, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
https://raw.githubusercontent.com/Jovanykoch/rules/rel/loc-cn.quanx, tag=direct, force-policy=direct, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
[rewrite_remote]
https://raw.githubusercontent.com/Jovanykoch/rules/rel/ext/bili.quanx, tag=bilibili, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
[server_local]
[filter_local]
host-suffix, local, direct
ip-cidr, 192.168.0.0/16, direct
ip-cidr, 10.0.0.0/8, direct
ip-cidr, 172.16.0.0/12, direct
ip-cidr, 127.0.0.0/8, direct
ip-cidr, 100.64.0.0/10, direct
ip-cidr, 224.0.0.0/4, direct
ip6-cidr, fe80::/10, direct
geoip, cn, direct
geoip, lan, direct
final, direct
[rewrite_local]
[task_local]
event-interaction https://ddgksf2013.top/scripts/server-info-pure.js, tag=节点详情(Pure), img-url=checkmark.shield.fill.system
event-interaction https://raw.githubusercontent.com/xream/scripts/main/surge/modules/network-info/net-lsp-x.js, tag=网络信息 𝕏, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.webp, enabled=false
event-interaction https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/geo_location.js, tag=GeoIP 查询, img-url=location.fill.viewfinder.system, enabled=true
event-interaction https://gist.githubusercontent.com/RavelloH/383354955aa3800e1d7e98666e11e16f/raw/block_check.js, tag=节点阻断检测, img-url=bolt.horizontal.icloud.fill.system, enabled=true
[mitm]
hostname = www.google.cn
passphrase = 
p12 = 
